FROM node:18-alpine AS builder

WORKDIR /app

ENV NODE_ENV development

COPY package*.json yarn.lock .npmrc ./
RUN yarn

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app .
COPY . .

EXPOSE 19998

CMD ["yarn", "start:dev"]