---
version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3
    ports:
      - 9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-manager:
    image: dockerkafka/kafka-manager
    environment:
    - ZK_HOSTS=zookeeper:2181
    ports:
      - "9000:9000"
    links:
      - zookeeper:zookeeper
      - kafka:kafka
    volumes:
      - ./image/conf:/opt/kafka-manager-1.2.7/conf