# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node JS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: danieljonsansom/kafka-api 
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run Tests
      run: |
        npm install
        npm run build
        npm test

    - name: Automated Version Bump                  # This action step reads and updates the version number acc to commit message
      id: version-bump
      uses: 'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Output Step                             # Optional: Prints the new version
      env:
        NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
      run: echo "new tag $NEW_TAG"
    
    - name: Login to Docker Hub
      run: docker login --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"

    - name: Build and push Docker image            # Builds and pushes the image to the conatiner registry
      uses: docker/build-push-action@v2
      with:
        context: .                        # Folder where the Dockerfile resides, use `/` if in root path
        tags: ${{ env.IMAGE_NAME }}:latest, ${{ env.IMAGE_NAME }}:${{ steps.version-bump.outputs.newTag }}